/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	versioned "github.com/intelligent-machine-learning/dlrover/go/client/clientset/versioned"
	internalinterfaces "github.com/intelligent-machine-learning/dlrover/go/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/intelligent-machine-learning/dlrover/go/client/listers/core/v1alpha1"
	apiv1alpha1 "github.com/intelligent-machine-learning/dlrover/go/elasticjob/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ElasticJobSpecInformer provides access to a shared informer and lister for
// ElasticJobSpecs.
type ElasticJobSpecInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ElasticJobSpecLister
}

type elasticJobSpecInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewElasticJobSpecInformer constructs a new informer for ElasticJobSpec type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewElasticJobSpecInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredElasticJobSpecInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredElasticJobSpecInformer constructs a new informer for ElasticJobSpec type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredElasticJobSpecInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().ElasticJobSpecs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CoreV1alpha1().ElasticJobSpecs(namespace).Watch(context.TODO(), options)
			},
		},
		&apiv1alpha1.ElasticJobSpec{},
		resyncPeriod,
		indexers,
	)
}

func (f *elasticJobSpecInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredElasticJobSpecInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *elasticJobSpecInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiv1alpha1.ElasticJobSpec{}, f.defaultInformer)
}

func (f *elasticJobSpecInformer) Lister() v1alpha1.ElasticJobSpecLister {
	return v1alpha1.NewElasticJobSpecLister(f.Informer().GetIndexer())
}
