/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/intelligent-machine-learning/dlrover/go/elasticjob/api/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ElasticJobListLister helps list ElasticJobLists.
// All objects returned here must be treated as read-only.
type ElasticJobListLister interface {
	// List lists all ElasticJobLists in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ElasticJobList, err error)
	// ElasticJobLists returns an object that can list and get ElasticJobLists.
	ElasticJobLists(namespace string) ElasticJobListNamespaceLister
	ElasticJobListListerExpansion
}

// elasticJobListLister implements the ElasticJobListLister interface.
type elasticJobListLister struct {
	indexer cache.Indexer
}

// NewElasticJobListLister returns a new ElasticJobListLister.
func NewElasticJobListLister(indexer cache.Indexer) ElasticJobListLister {
	return &elasticJobListLister{indexer: indexer}
}

// List lists all ElasticJobLists in the indexer.
func (s *elasticJobListLister) List(selector labels.Selector) (ret []*v1alpha1.ElasticJobList, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ElasticJobList))
	})
	return ret, err
}

// ElasticJobLists returns an object that can list and get ElasticJobLists.
func (s *elasticJobListLister) ElasticJobLists(namespace string) ElasticJobListNamespaceLister {
	return elasticJobListNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ElasticJobListNamespaceLister helps list and get ElasticJobLists.
// All objects returned here must be treated as read-only.
type ElasticJobListNamespaceLister interface {
	// List lists all ElasticJobLists in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ElasticJobList, err error)
	// Get retrieves the ElasticJobList from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ElasticJobList, error)
	ElasticJobListNamespaceListerExpansion
}

// elasticJobListNamespaceLister implements the ElasticJobListNamespaceLister
// interface.
type elasticJobListNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ElasticJobLists in the indexer for a given namespace.
func (s elasticJobListNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ElasticJobList, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ElasticJobList))
	})
	return ret, err
}

// Get retrieves the ElasticJobList from the indexer for a given namespace and name.
func (s elasticJobListNamespaceLister) Get(name string) (*v1alpha1.ElasticJobList, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("elasticjoblist"), name)
	}
	return obj.(*v1alpha1.ElasticJobList), nil
}
