/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/intelligent-machine-learning/dlrover/go/elasticjob/api/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ElasticJobSpecLister helps list ElasticJobSpecs.
// All objects returned here must be treated as read-only.
type ElasticJobSpecLister interface {
	// List lists all ElasticJobSpecs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ElasticJobSpec, err error)
	// ElasticJobSpecs returns an object that can list and get ElasticJobSpecs.
	ElasticJobSpecs(namespace string) ElasticJobSpecNamespaceLister
	ElasticJobSpecListerExpansion
}

// elasticJobSpecLister implements the ElasticJobSpecLister interface.
type elasticJobSpecLister struct {
	indexer cache.Indexer
}

// NewElasticJobSpecLister returns a new ElasticJobSpecLister.
func NewElasticJobSpecLister(indexer cache.Indexer) ElasticJobSpecLister {
	return &elasticJobSpecLister{indexer: indexer}
}

// List lists all ElasticJobSpecs in the indexer.
func (s *elasticJobSpecLister) List(selector labels.Selector) (ret []*v1alpha1.ElasticJobSpec, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ElasticJobSpec))
	})
	return ret, err
}

// ElasticJobSpecs returns an object that can list and get ElasticJobSpecs.
func (s *elasticJobSpecLister) ElasticJobSpecs(namespace string) ElasticJobSpecNamespaceLister {
	return elasticJobSpecNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ElasticJobSpecNamespaceLister helps list and get ElasticJobSpecs.
// All objects returned here must be treated as read-only.
type ElasticJobSpecNamespaceLister interface {
	// List lists all ElasticJobSpecs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ElasticJobSpec, err error)
	// Get retrieves the ElasticJobSpec from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ElasticJobSpec, error)
	ElasticJobSpecNamespaceListerExpansion
}

// elasticJobSpecNamespaceLister implements the ElasticJobSpecNamespaceLister
// interface.
type elasticJobSpecNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ElasticJobSpecs in the indexer for a given namespace.
func (s elasticJobSpecNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ElasticJobSpec, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ElasticJobSpec))
	})
	return ret, err
}

// Get retrieves the ElasticJobSpec from the indexer for a given namespace and name.
func (s elasticJobSpecNamespaceLister) Get(name string) (*v1alpha1.ElasticJobSpec, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("elasticjobspec"), name)
	}
	return obj.(*v1alpha1.ElasticJobSpec), nil
}
