/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ElasticJobListerExpansion allows custom methods to be added to
// ElasticJobLister.
type ElasticJobListerExpansion interface{}

// ElasticJobNamespaceListerExpansion allows custom methods to be added to
// ElasticJobNamespaceLister.
type ElasticJobNamespaceListerExpansion interface{}

// ElasticJobListListerExpansion allows custom methods to be added to
// ElasticJobListLister.
type ElasticJobListListerExpansion interface{}

// ElasticJobListNamespaceListerExpansion allows custom methods to be added to
// ElasticJobListNamespaceLister.
type ElasticJobListNamespaceListerExpansion interface{}

// ElasticJobSpecListerExpansion allows custom methods to be added to
// ElasticJobSpecLister.
type ElasticJobSpecListerExpansion interface{}

// ElasticJobSpecNamespaceListerExpansion allows custom methods to be added to
// ElasticJobSpecNamespaceLister.
type ElasticJobSpecNamespaceListerExpansion interface{}
